<a href="https://colab.research.google.com/github/Raihan-J/Python-Spoken-Tutorial/blob/master/Accessing%20Parts%20Of%20Arrays/Accessing%20Parts%20Of%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(1,6)
C = np.arange(1,26).reshape(5,5)

In [3]:
A

array([1, 2, 3, 4, 5])

In [4]:
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
A[2]

3

In [6]:
C[2,3]

14

In [7]:
A[2] = -3

In [8]:
C[2,3] = -14

In [9]:
A

array([ 1,  2, -3,  4,  5])

In [10]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [11]:
C[2]

array([ 11,  12,  13, -14,  15])

In [12]:
C[4]

array([21, 22, 23, 24, 25])

In [13]:
C[-1] = [0,0,0,0,0]
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [  0,   0,   0,   0,   0]])

In [14]:
C[-1] = 2
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [  2,   2,   2,   2,   2]])

**Slicing of an Array**

In [15]:
C[0:3,2]

array([ 3,  8, 13])

In [16]:
C[2,0:3]

array([11, 12, 13])

**Assignment-1**

In [17]:
C[1,1:3]

array([7, 8])

In [18]:
C[0:4,0]

array([ 1,  6, 11, 16])

In [19]:
C[1:5,0]

array([ 6, 11, 16,  2])

In [20]:
C[1:,0]

array([ 6, 11, 16,  2])

**Assignment-2**

In [21]:
C[1:3,2:4]

array([[  8,   9],
       [ 13, -14]])

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [22]:
C[::2,::]

array([[  1,   2,   3,   4,   5],
       [ 11,  12,  13, -14,  15],
       [  2,   2,   2,   2,   2]])

In [23]:
C[1::2,::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

**Assignment-3**

In [24]:
C[::3,1::3]

array([[ 2,  5],
       [17, 20]])

In [25]:
C[::4,1:4]

array([[2, 3, 4],
       [2, 2, 2]])