<a href="https://colab.research.google.com/github/Raihan-J/Python-Spoken-Tutorial/blob/master/Getting%20Started%20with%20Arrays/Getting%20Started%20with%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Arange Method**

In [4]:
ar = np.arange(1,9)

print(ar)

[1 2 3 4 5 6 7 8]


**Reshape Method**

In [5]:
ar.reshape(2,4)
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
ar.shape = (2,4)
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a2.shape

(2, 4)

**Assignment-1**

In [8]:
a1.shape

(4,)

In [9]:
ar.shape

(2, 4)

In [10]:
a3 = np.array([1,2,3,'a sting'])
a3

array(['1', '2', '3', 'a sting'], dtype='<U21')

**Identity Method**

In [11]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

**Zeros Method**

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
a1

array([1, 2, 3, 4])

In [14]:
a1 * 2
a1

array([1, 2, 3, 4])

In [15]:
a1 + 2
a1

array([1, 2, 3, 4])

In [16]:
a1 +=2
a1

array([3, 4, 5, 6])

In [17]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

a1+a2

array([ 6,  8, 10, 12])

In [18]:
a1 * a2

array([ 5, 12, 21, 32])