<a href="https://colab.research.google.com/github/Raihan-J/Python-Spoken-Tutorial/blob/master/Statistics/Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!rm football.*
!wget https://raw.githubusercontent.com/Raihan-J/Python-Spoken-Tutorial/master/Statistics/football.txt
!rm student_record.*
!wget https://raw.githubusercontent.com/Raihan-J/Python-Spoken-Tutorial/master/Statistics/student_record.txt

rm: cannot remove 'football.*': No such file or directory
--2020-09-01 21:37:17--  https://raw.githubusercontent.com/Raihan-J/Python-Spoken-Tutorial/master/Statistics/football.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160 [text/plain]
Saving to: ‘football.txt’

football.txt        100%[===================>]     160  --.-KB/s    in 0s      

2020-09-01 21:37:17 (7.61 MB/s) - ‘football.txt’ saved [160/160]

rm: cannot remove 'student_record.*': No such file or directory
--2020-09-01 21:37:18--  https://raw.githubusercontent.com/Raihan-J/Python-Spoken-Tutorial/master/Statistics/student_record.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (ra

In [ ]:
!pip3 install numpy

In [3]:
import numpy as np

L = np.loadtxt("student_record.txt", usecols=(3,4,5,6,7), delimiter=';')

In [4]:
L

array([[53., 36., 28., 16., 44.],
       [58., 37., 42., 35., 40.],
       [72., 56., 71., 55., 70.],
       ...,
       [49., 39., 12., 20., 24.],
       [33., 36., 22., 15., 35.],
       [17., 14., 15., 14., 20.]])

In [5]:
L.shape

(185667, 5)

In [6]:
L[0]

array([53., 36., 28., 16., 44.])

In [7]:
totalmarks = sum(L[0])

In [8]:
totalmarks

177.0

In [9]:
np.mean(L[0])

35.4

In [10]:
np.mean(L,0)

array([73.55452504, 53.79828941, 62.83342759, 50.69806158, 63.17056881])

In [11]:
L[:,0]

array([53., 58., 72., ..., 49., 33., 17.])

In [12]:
np.median(L[:,0])

76.0

In [13]:
np.median(L,0)

array([76., 53., 62., 49., 64.])

In [14]:
np.std(L[:,0])

14.149386756586962

In [15]:
np.std(L,0)

array([14.14938676, 15.40067866, 23.49972527, 20.06422781, 16.94574819])

**Assignment-1**

In [16]:
L = np.loadtxt("football.txt", usecols=(1,2), delimiter=',')

In [17]:
np.sum(L,1)

array([153.,  99.,  86.,  47.,  88.,  99.])

In [18]:
np.mean(L,0)

array([49.33333333, 46.        ])

In [19]:
np.std(L,0)

array([20.72572208, 15.57776193])