<a href="https://colab.research.google.com/github/Raihan-J/Python-Spoken-Tutorial/blob/master/Basic%20Matrix%20Operations/Basic%20Matrix%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import matrix

In [2]:
m1 = matrix([1,2,3,4])

m1

matrix([[1, 2, 3, 4]])

In [3]:
m1.shape

(1, 4)

In [4]:
l1 = [[1,2,3,4],[5,6,7,8]]
m2 = matrix(l1)
print(m2)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
from numpy import asmatrix,arange

m2_array = asmatrix(arange(1,9).reshape(2,4))
m2_array

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

**Assignment-1**

In [6]:
m3 = asmatrix(arange(5,13).reshape(2,4))

m3

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [7]:
m3 + m2

matrix([[ 6,  8, 10, 12],
        [14, 16, 18, 20]])

In [8]:
m3 - m2

matrix([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [9]:
6.5* m2

matrix([[ 6.5, 13. , 19.5, 26. ],
        [32.5, 39. , 45.5, 52. ]])

In [10]:
m2.shape

(2, 4)

In [11]:
m4 = asmatrix(arange(1,9).reshape(4,2))
m4.shape

(4, 2)

In [12]:
m2 * m4

matrix([[ 50,  60],
        [114, 140]])

In [13]:
print(m4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
print(m4.T)

[[1 3 5 7]
 [2 4 6 8]]


**Assignment-2**

In [15]:
from numpy.linalg import det

m5 = matrix([[2,-3,1],[2,0,-1],[1,4,5]])
det(m5)

49.000000000000014

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [16]:
from numpy.linalg import inv

im5 = inv(m5)

im5

matrix([[ 0.08163265,  0.3877551 ,  0.06122449],
        [-0.2244898 ,  0.18367347,  0.08163265],
        [ 0.16326531, -0.2244898 ,  0.12244898]])

In [17]:
from numpy import eye,allclose

allclose(im5 * m5, asmatrix(eye(3)))

True

**Eigen Values and Eigen Vectors**

In [18]:
from numpy import diag
from numpy.linalg import eig

m6=asmatrix(diag((1,2,3)))

eig(m6)

(array([1., 2., 3.]), matrix([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [19]:
eig_value = eig(m6)[0]
eig_value

array([1., 2., 3.])

In [20]:
eig_vector = eig(m6)[1]

eig_vector

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
from numpy.linalg import eigvals
eig_value1 = eigvals(m6)
eig_value1

array([1., 2., 3.])